"""Data types of the domain core: the vocabulary of ``docs/architecture.md``.

This package holds types only. There is no arbiter, no schedule, no tracker
logic and no geometry here; the blocks that build them exchange the types
defined below. Every type is immutable, validates itself on construction and
compares by value.

Import from the package, not from its modules: ``from ...core.model import
Position``. The modules exist so that blocks that work in parallel edit
different files. Their dependencies run one way:

``_validation`` ← ``_data`` ← ``values`` ← ``decision`` ← ``observation`` ←
``tracking`` ← ``state`` ← ``snapshot``. ``tracking`` holds what the movement
tracker keeps per member, what it measures and the events it reports;
``state`` also uses ``window`` (the end rule of the manual override). ``functions`` depends on nothing; ``window`` depends
on ``_validation``, ``functions`` and ``values``, ``controls`` on
``_validation`` only; ``decision`` also uses ``functions``, and ``snapshot``
also uses ``controls`` and ``almanac``. ``schedule`` (the settings of the
schedule as values) depends on ``_validation`` and ``values`` and is used by
``window``; ``almanac`` depends on ``_validation`` and ``_data``. ``geometry``
(the measurements of shading as values) depends on ``_validation`` and
``values`` and is used by ``window``.

Conventions that hold for the whole package:

- A position is an integer from 0 to 100; 100 is fully open, 0 fully closed.
  Positions of members are on the motor scale.
- Every datetime is timezone-aware. A naive datetime is rejected. Persisted
  instants are kept in UTC; the time of a world snapshot keeps the local zone
  of the installation.
- A member is identified by a string that the core treats as opaque.
- Nothing converts "unknown" or "unavailable" into a number or a boolean.
"""

from ._data import JsonObject, JsonValue
from .almanac import ElevationPassage, SunAlmanac, SunDay
from .controls import ControlLevel, Controls, OperatingMode
from .decision import (
    CONSTRAINT_REASONS,
    GATE_RULE_REASONS,
    Constraint,
    ConstraintResult,
    Decision,
    Direction,
    EvaluationFault,
    EvaluationStage,
    GateKind,
    GateOutcome,
    GateRule,
    Layer,
    LayerReason,
    MemberTarget,
    Wish,
    WishClass,
    WishKind,
)
from .functions import FaultBehavior, FunctionId
from .geometry import (
    GEOMETRY_FIELDS,
    GEOMETRY_PREFIX,
    MAX_AMPLIFICATION_CAP,
    MAX_MEASURED_LENGTH,
    MEMBER_MEASUREMENT_FIELDS,
    MIN_CALIBRATION_SPAN,
    NO_CALIBRATION,
    NO_MEASUREMENTS,
    GeometryRuleError,
    GlassCalibration,
    MemberGlass,
    MemberGlassError,
    MemberMeasurements,
    ShadingGeometrySettings,
    member_glass_for,
)
from .observation import (
    CommandResult,
    MemberCommand,
    MemberObservation,
    MembersAtTargets,
    MissedCommand,
    MovementState,
    Observation,
    OwnCommand,
    TravelDirection,
    WindowObservation,
)
from .schedule import (
    MAX_RANDOM_OFFSET,
    MAX_SUN_OFFSET_MINUTES,
    MAX_TRIGGER_ELEVATION,
    TRIGGER_FIELDS,
    DayTriggers,
    ScheduleProfile,
    ScheduleRuleError,
    ScheduleSettings,
    ScheduleTargets,
    Trigger,
    TriggerKind,
)
from .snapshot import WorldSnapshot
from .state import (
    WINDOW_STATE_SCHEMA_VERSION,
    ComfortMovementCount,
    DayType,
    ExternalRequest,
    HeldInput,
    LatchedDayType,
    ManualOverrideDam,
    MemberState,
    PersonAtWindowDam,
    PositionOwner,
    PositionReference,
    ProtectionEventState,
    ProtectionEventStatus,
    ShadingEpisodeState,
    SimulatedState,
    SolarHeatingEpisodeState,
    Transition,
    WindowState,
)
from .tracking import (
    SELF_MEASUREMENT_SAMPLES,
    MemberTracking,
    SampleStatistic,
    SelfMeasurement,
    TrackerEvent,
    TrackerPhase,
)
from .values import (
    FULLY_CLOSED,
    FULLY_OPEN,
    AnySourceValue,
    MissingSourceValueError,
    Position,
    SourceScalar,
    SourceState,
    SourceValue,
    SunPosition,
)
from .window import (
    BLIND_SOURCE,
    DEFAULT_COMFORT_MOVEMENTS_THRESHOLD,
    DEFAULT_OVERRIDE_MINUTES,
    DEFAULT_PERSON_AT_WINDOW,
    DEFAULT_ROOM_EMPTY_AFTER,
    DEFAULT_STAGGER_GAP,
    DEFAULT_TOLERANCE_CALCULATED,
    DEFAULT_TOLERANCE_MEASURED,
    DEFAULT_TRAVEL_TIME,
    MAX_COMFORT_MOVEMENTS_THRESHOLD,
    MAX_DAM_DURATION,
    MAX_REPORTING_TIME,
    MAX_STAGGER_GAP,
    MAX_STATED_TOLERANCE,
    MAX_TOLERANCE,
    MAX_TRAVEL_TIME,
    MIN_DAM_DURATION,
    MIN_TOLERANCE,
    MIN_TRAVEL_TIME,
    SCHEDULE_DAY_TYPES,
    SCHEDULE_EDGES,
    BlindSource,
    CapabilityProfile,
    CapabilityState,
    CoveringType,
    FrostSettings,
    ManualOverrideSettings,
    MemberConfig,
    MotorProtectionSettings,
    OverrideEndRule,
    PositionSource,
    PositionUpdates,
    ReportingKind,
    SettingsCombinationError,
    TemperatureTier,
    TransitReporting,
    WindowCapabilities,
    WindowCapabilityStates,
    WindowConfig,
)

__all__ = [
    "BLIND_SOURCE",
    "CONSTRAINT_REASONS",
    "DEFAULT_COMFORT_MOVEMENTS_THRESHOLD",
    "DEFAULT_OVERRIDE_MINUTES",
    "DEFAULT_PERSON_AT_WINDOW",
    "DEFAULT_ROOM_EMPTY_AFTER",
    "DEFAULT_STAGGER_GAP",
    "DEFAULT_TOLERANCE_CALCULATED",
    "DEFAULT_TOLERANCE_MEASURED",
    "DEFAULT_TRAVEL_TIME",
    "FULLY_CLOSED",
    "FULLY_OPEN",
    "GATE_RULE_REASONS",
    "GEOMETRY_FIELDS",
    "GEOMETRY_PREFIX",
    "MAX_AMPLIFICATION_CAP",
    "MAX_COMFORT_MOVEMENTS_THRESHOLD",
    "MAX_DAM_DURATION",
    "MAX_MEASURED_LENGTH",
    "MAX_RANDOM_OFFSET",
    "MAX_REPORTING_TIME",
    "MAX_STAGGER_GAP",
    "MAX_STATED_TOLERANCE",
    "MAX_SUN_OFFSET_MINUTES",
    "MAX_TOLERANCE",
    "MAX_TRAVEL_TIME",
    "MAX_TRIGGER_ELEVATION",
    "MEMBER_MEASUREMENT_FIELDS",
    "MIN_CALIBRATION_SPAN",
    "MIN_DAM_DURATION",
    "MIN_TOLERANCE",
    "MIN_TRAVEL_TIME",
    "NO_CALIBRATION",
    "NO_MEASUREMENTS",
    "SCHEDULE_DAY_TYPES",
    "SCHEDULE_EDGES",
    "SELF_MEASUREMENT_SAMPLES",
    "TRIGGER_FIELDS",
    "WINDOW_STATE_SCHEMA_VERSION",
    "AnySourceValue",
    "BlindSource",
    "CapabilityProfile",
    "CapabilityState",
    "ComfortMovementCount",
    "CommandResult",
    "Constraint",
    "ConstraintResult",
    "ControlLevel",
    "Controls",
    "CoveringType",
    "DayTriggers",
    "DayType",
    "Decision",
    "Direction",
    "ElevationPassage",
    "EvaluationFault",
    "EvaluationStage",
    "ExternalRequest",
    "FaultBehavior",
    "FrostSettings",
    "FunctionId",
    "GateKind",
    "GateOutcome",
    "GateRule",
    "GeometryRuleError",
    "GlassCalibration",
    "HeldInput",
    "JsonObject",
    "JsonValue",
    "LatchedDayType",
    "Layer",
    "LayerReason",
    "ManualOverrideDam",
    "ManualOverrideSettings",
    "MemberCommand",
    "MemberConfig",
    "MemberGlass",
    "MemberGlassError",
    "MemberMeasurements",
    "MemberObservation",
    "MemberState",
    "MemberTarget",
    "MemberTracking",
    "MembersAtTargets",
    "MissedCommand",
    "MissingSourceValueError",
    "MotorProtectionSettings",
    "MovementState",
    "Observation",
    "OperatingMode",
    "OverrideEndRule",
    "OwnCommand",
    "PersonAtWindowDam",
    "Position",
    "PositionOwner",
    "PositionReference",
    "PositionSource",
    "PositionUpdates",
    "ProtectionEventState",
    "ProtectionEventStatus",
    "ReportingKind",
    "SampleStatistic",
    "ScheduleProfile",
    "ScheduleRuleError",
    "ScheduleSettings",
    "ScheduleTargets",
    "SelfMeasurement",
    "SettingsCombinationError",
    "ShadingEpisodeState",
    "ShadingGeometrySettings",
    "SimulatedState",
    "SolarHeatingEpisodeState",
    "SourceScalar",
    "SourceState",
    "SourceValue",
    "SunAlmanac",
    "SunDay",
    "SunPosition",
    "TemperatureTier",
    "TrackerEvent",
    "TrackerPhase",
    "TransitReporting",
    "Transition",
    "TravelDirection",
    "Trigger",
    "TriggerKind",
    "WindowCapabilities",
    "WindowCapabilityStates",
    "WindowConfig",
    "WindowObservation",
    "WindowState",
    "Wish",
    "WishClass",
    "WishKind",
    "WorldSnapshot",
    "member_glass_for",
]
