"""Guard: no tracked file contains data of a real installation or machine.

The repository is public. This script reads every file that git tracks and
fails when a line looks like it came from a real installation or from
somebody's computer. The patterns are generic shapes, not a list of known
values: a list of real values would itself be instance data.

A finding names the file, the line and the kind of pattern, but never the text
that matched, because the output of this script ends up in public CI logs.

The check is a net with holes. It cannot know that a harmless looking room
name is real. It complements the rule in ``tasks/README.md``, it does not
replace reading what you publish.

Run it from anywhere inside the checkout:
``python scripts/check_instance_data.py``. It needs git and the standard
library.
"""

import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]

# The lock file is generated by uv and consists of package names, versions,
# URLs of the package index and hashes. Nothing in it is written by hand, and
# long hexadecimal hashes would only produce false findings.
SKIPPED_FILES = frozenset({"uv.lock"})

_ENTITY_DOMAINS = (
    "binary_sensor|button|climate|cover|device_tracker|event|fan|input_boolean|"
    "input_number|input_select|light|lock|media_player|number|person|scene|"
    "select|sensor|sun|switch|update|weather|zone"
)

# Documentation addresses that are reserved for examples and therefore allowed.
_ALLOWED_MAIL_DOMAINS = ("example.com", "example.org", "example.net")
# The no-reply address in the co-author trailer of generated commits may also
# appear in contributor documentation.
_ALLOWED_MAIL_SUFFIXES = ("noreply@anthropic.com", "users.noreply.github.com")
# The IPv6 documentation range, and the host names every installation has.
_ALLOWED_IPV6_PREFIX = "2001:db8:"
_ALLOWED_HOST_NAMES = ("homeassistant.local", "example.local")

PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "private IPv4 address",
        re.compile(
            r"(?<![\d.])(?:10\.\d{1,3}|192\.168|172\.(?:1[6-9]|2\d|3[01]))"
            r"\.\d{1,3}\.\d{1,3}(?![\d.])"
        ),
    ),
    (
        "hardware (MAC) address",
        re.compile(
            r"(?<![0-9A-Fa-f:-])(?:[0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}(?![:-])"
        ),
    ),
    (
        "IPv6 address",
        re.compile(
            r"(?<![\w:.])(?:"
            r"(?:[0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}"
            r"|(?:[0-9A-Fa-f]{1,4}:){1,6}:(?:[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4}){0,5})?"
            r")(?![\w:])"
        ),
    ),
    (
        "host name in the local network",
        re.compile(r"(?<![\w.-])[A-Za-z0-9][A-Za-z0-9-]*\.local(?![\w.(-])"),
    ),
    # A plain number with many decimals is not reported: constants of the
    # domain core look like that. A coordinate is recognized by its company.
    (
        "pair of coordinates",
        re.compile(
            r"(?<![\w.])-?\d{1,2}\.\d{4,}\s*[,;/ ]\s*-?\d{1,3}\.\d{4,}(?![\w.])"
        ),
    ),
    (
        "coordinate next to a latitude or longitude key",
        re.compile(
            r"(?i)(?<![a-z])(?:lat|latitude|lon|lng|long|longitude)[\"']?\s*[:=]\s*"
            r"[\"']?-?\d{1,3}\.\d{3,}"
        ),
    ),
    (
        "entity ID with a serial-number-like part",
        re.compile(
            rf"\b(?:{_ENTITY_DOMAINS})\.[a-z0-9_]*?"
            r"(?:\d{5,}|(?=[0-9a-f]*\d)(?=[0-9a-f]*[a-f])[0-9a-f]{8,})[a-z0-9_]*"
        ),
    ),
    (
        "path with a Windows drive letter",
        re.compile(r"(?<![A-Za-z])[A-Za-z]:[\\/]{1,2}[A-Za-z_]"),
    ),
    (
        "path inside a user's home directory",
        re.compile(r"(?:/home/|/Users/|\\Users\\)[A-Za-z0-9][\w.-]*"),
    ),
    (
        "path of a mounted Windows drive",
        re.compile(r"/mnt/[a-z]/"),
    ),
    (
        "e-mail address",
        re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+"),
    ),
)


@dataclass(frozen=True)
class Finding:
    """One suspicious line. The matched text is deliberately not kept."""

    path: str
    line: int
    kind: str

    def __str__(self) -> str:
        """Render as ``path:line: kind``."""
        return f"{self.path}:{self.line}: looks like: {self.kind}"


def _is_allowed(kind: str, matched: str) -> bool:
    lowered = matched.lower()
    if kind == "IPv6 address":
        return lowered.startswith(_ALLOWED_IPV6_PREFIX)
    if kind == "host name in the local network":
        return lowered in _ALLOWED_HOST_NAMES
    if kind != "e-mail address":
        return False
    return lowered.endswith(_ALLOWED_MAIL_SUFFIXES) or lowered.rsplit("@", 1)[
        -1
    ].endswith(_ALLOWED_MAIL_DOMAINS)


def check_text(text: str, path: str) -> list[Finding]:
    """Check the content of one file."""
    findings: list[Finding] = []
    for number, line in enumerate(text.splitlines(), start=1):
        for kind, pattern in PATTERNS:
            if any(not _is_allowed(kind, m.group()) for m in pattern.finditer(line)):
                findings.append(Finding(path, number, kind))
    return findings


class GitUnavailableError(RuntimeError):
    """git could not list the tracked files."""


def tracked_files(root: Path) -> list[str]:
    """Return the paths git tracks below ``root``, relative to it."""
    try:
        result = subprocess.run(
            ["git", "ls-files", "-z"],  # noqa: S607 - git is found through PATH
            cwd=root,
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as error:
        raise GitUnavailableError(
            "git cannot list the tracked files here. Run this script where git "
            "works for the checkout (on Windows with WSL: on the Windows side)"
        ) from error
    return [name for name in result.stdout.decode("utf-8").split("\0") if name]


def check_tree(root: Path, paths: list[str]) -> list[Finding]:
    """Check the given files below ``root``; binary files are skipped."""
    findings: list[Finding] = []
    for relative in sorted(paths):
        if relative in SKIPPED_FILES:
            continue
        file = root / relative
        if not file.is_file():
            continue
        try:
            text = file.read_bytes().decode("utf-8")
        except UnicodeDecodeError:
            continue
        findings += check_text(text, relative)
    return findings


def main() -> int:
    """Run the guard on this repository."""
    try:
        paths = tracked_files(REPOSITORY_ROOT)
    except GitUnavailableError as error:
        sys.stdout.write(f"instance data: {error}\n")
        return 2
    findings = check_tree(REPOSITORY_ROOT, paths)
    for finding in findings:
        sys.stdout.write(f"{finding}\n")
    if findings:
        sys.stdout.write(f"instance data: {len(findings)} suspicious line(s)\n")
        return 1
    sys.stdout.write("instance data: ok\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
